name: Polmodor
options:
  bundleIdPrefix: com
  deploymentTarget:
    iOS: 18.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

settings:
  base:
    DEVELOPMENT_TEAM: K9878XM64L
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    TARGETED_DEVICE_FAMILY: "1"
    GENERATE_INFOPLIST_FILE: YES
    ENABLE_BITCODE: NO
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    SWIFT_STRICT_CONCURRENCY: complete

configs:
  Debug: debug
  Release: release

packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    from: 0.54.0

targets:
  Polmodor:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.polmodor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
        SWIFT_STRICT_CONCURRENCY: complete

    info:
      path: Sources/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: "LaunchScreen"
        NSSupportsLiveActivities: true
        UIBackgroundModes:
          - remote-notification
          - fetch
          - processing
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - polmodor
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSUserNotificationsUsageDescription: "We need to send you notifications when your Pomodoro timer completes."

    preBuildScripts:
      - name: SwiftLint
        script: |
          if [[ -f "${PODS_ROOT}/SwiftLint/swiftlint" ]]; then
            "${PODS_ROOT}/SwiftLint/swiftlint"
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        basedOnDependencyAnalysis: false

  PolmodorWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: 18.0
    sources:
      - Widget
    dependencies:
      - target: Polmodor
    settings:
      base:
        INFOPLIST_FILE: Widget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.polmodor.widget
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_PREVIEWS: YES
        SKIP_INSTALL: YES
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        NSSupportsLiveActivities: true

schemes:
  Polmodor:
    build:
      targets:
        Polmodor: all
        PolmodorWidget: all
      parallelizeBuild: true
    run:
      config: Debug
      environmentVariables:
        SWIFT_DEBUG_FULLPATH: YES
    test:
      config: Debug
      targets:
        - PolmodorTests
        - PolmodorUITests
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
